### ISSUE TITLE
import regex failing in tox tests - but succeeds when pytest is run.

### ISSUE THREAD

**Issue by vvasuki** [sanskrit-coders/indic_transliteration#7]
Consider [this](https://travis-ci.org/sanskrit-coders/indic_transliteration/jobs/307685569) failed travis/ tox test . This is what happens when I run clone the [repo](https://github.com/sanskrit-coders/indic_transliteration) and run `tox` - yet running `pytest` works fine. setup.py includes `regex` as a dependency. Any ideas (@kmadathil @codito @drdhaval2785 @shreevatsa  ) ?

**Comment by codito** [comment]
This issue is fixed in [newer](https://travis-ci.org/sanskrit-coders/indic_transliteration/builds/307721390?utm_source=github_status&utm_medium=notification) travis builds, also validated in my machine. The [older](https://travis-ci.org/sanskrit-coders/indic_transliteration/builds/307685564) travis build was using a version of source repo which didn't have the deps mentioned in setup.py (commit 80150eceafdb4a8f3346d145a7ec627e5d3a2251).

**Comment by vvasuki** [comment]
Thanks, @codito ! It's great to see travis+tox succeed. I'd arrived at that understanding of `tox` earlier as well - but am stumped by why tox still fails locally and does not install the regex package mentioned in setup.py..

**Comment by vvasuki** [comment]
Ah - Doing `rm -R .tox; tox` worked fine. Thanks!
